export interface EvmChainConfig {
  name: string;
  label: string;
  chainId: number;
  rpcUrl: string;
  /** LayerZero V2 endpoint ID, required for direct on-chain OFT interactions. */
  endpointId: number;
  /** Transaction URL template for task panel links. */
  explorerTxUrl?: string;
}

export const evmChains: Record<string, EvmChainConfig> = {
  "abstract": {
    name: "abstract",
    label: "Abstract",
    chainId: 2741,
    rpcUrl: "https://api.mainnet.abs.xyz",
    endpointId: 30324,
    explorerTxUrl: "https://abscan.org/tx/{tx}",
  },
  "ape": {
    name: "ape",
    label: "Ape",
    chainId: 33139,
    rpcUrl: "https://rpc.apechain.com",
    endpointId: 30312,
    explorerTxUrl: "https://apescan.io/tx/{tx}",
  },
  "apexfusionnexus": {
    name: "apexfusionnexus",
    label: "Apex Fusion Nexus",
    chainId: 9069,
    rpcUrl: "https://rpc.nexus.mainnet.apexfusion.org/",
    endpointId: 30384,
    explorerTxUrl: "https://explorer.nexus.mainnet.apexfusion.org/tx/{tx}",
  },
  "arbitrum": {
    name: "arbitrum",
    label: "Arbitrum",
    chainId: 42161,
    rpcUrl: "https://arbitrum-one-rpc.publicnode.com",
    endpointId: 30110,
    explorerTxUrl: "https://arbiscan.io/tx/{tx}",
  },
  "astar": {
    name: "astar",
    label: "Astar",
    chainId: 592,
    rpcUrl: "https://rpc.astar.network:8545",
    endpointId: 30210,
    explorerTxUrl: "https://astar.subscan.io/evm/tx/{tx}",
  },
  "aurora": {
    name: "aurora",
    label: "Near Aurora",
    chainId: 1313161554,
    rpcUrl: "https://aurora.drpc.org",
    endpointId: 30211,
    explorerTxUrl: "https://explorer.aurora.dev/tx/{tx}",
  },
  "avalanche": {
    name: "avalanche",
    label: "Avalanche",
    chainId: 43114,
    rpcUrl: "https://avalanche-c-chain-rpc.publicnode.com",
    endpointId: 30106,
    explorerTxUrl: "https://snowscan.xyz/tx/{tx}",
  },
  "bahamut": {
    name: "bahamut",
    label: "Bahamut",
    chainId: 5165,
    rpcUrl: "https://rpc1.bahamut.io",
    endpointId: 30363,
    explorerTxUrl: "https://ftnscan.com/tx/{tx}",
  },
  "base": {
    name: "base",
    label: "Base",
    chainId: 8453,
    rpcUrl: "https://base-rpc.publicnode.com",
    endpointId: 30184,
    explorerTxUrl: "https://basescan.org/tx/{tx}",
  },
  "bb1": {
    name: "bb1",
    label: "inEVM",
    chainId: 2525,
    rpcUrl: "https://mainnet.rpc.inevm.com/http",
    endpointId: 30234,
  },
  "beam": {
    name: "beam",
    label: "Beam",
    chainId: 4337,
    rpcUrl: "https://build.onbeam.com/rpc",
    endpointId: 30198,
    explorerTxUrl: "https://subnets.avax.network/beam/tx/{tx}",
  },
  "bera": {
    name: "bera",
    label: "Berachain",
    chainId: 80094,
    rpcUrl: "https://rpc.berachain.com",
    endpointId: 30362,
    explorerTxUrl: "https://berascan.com/tx/{tx}",
  },
  "bevm": {
    name: "bevm",
    label: "Bevm",
    chainId: 11501,
    rpcUrl: "https://rpc-mainnet-1.geb.network/",
    endpointId: 30317,
    explorerTxUrl: "https://scan.geb.network/tx/{tx}",
  },
  "bitlayer": {
    name: "bitlayer",
    label: "Bitlayer",
    chainId: 200901,
    rpcUrl: "https://rpc.bitlayer.org",
    endpointId: 30314,
    explorerTxUrl: "https://www.btrscan.com/tx/{tx}",
  },
  "blast": {
    name: "blast",
    label: "Blast",
    chainId: 81457,
    rpcUrl: "https://blast-rpc.publicnode.com",
    endpointId: 30243,
    explorerTxUrl: "https://blastscan.io/tx/{tx}",
  },
  "bob": {
    name: "bob",
    label: "BOB",
    chainId: 60808,
    rpcUrl: "https://rpc.gobob.xyz",
    endpointId: 30279,
    explorerTxUrl: "https://explorer.gobob.xyz/tx/{tx}",
  },
  "botanix": {
    name: "botanix",
    label: "Botanix",
    chainId: 3637,
    rpcUrl: "https://rpc.botanixlabs.com",
    endpointId: 30376,
    explorerTxUrl: "https://botanixscan.io/tx/{tx}",
  },
  "bouncebit": {
    name: "bouncebit",
    label: "Bouncebit",
    chainId: 6001,
    rpcUrl: "https://fullnode-mainnet.bouncebitapi.com/",
    endpointId: 30293,
    explorerTxUrl: "https://bbscan.io/tx/{tx}",
  },
  "bsc": {
    name: "bsc",
    label: "BNB Smart Chain",
    chainId: 56,
    rpcUrl: "https://bsc-rpc.publicnode.com",
    endpointId: 30102,
    explorerTxUrl: "https://bscscan.com/tx/{tx}",
  },
  "camp": {
    name: "camp",
    label: "Camp",
    chainId: 484,
    rpcUrl: "https://rpc.camp.raas.gelato.cloud",
    endpointId: 30381,
    explorerTxUrl: "https://camp.cloud.blockscout.com/tx/{tx}",
  },
  "canto": {
    name: "canto",
    label: "Canto",
    chainId: 7700,
    rpcUrl: "https://canto-rpc.ansybl.io",
    endpointId: 30159,
    explorerTxUrl: "https://www.oklink.com/canto/tx/{tx}",
  },
  "celo": {
    name: "celo",
    label: "Celo",
    chainId: 42220,
    rpcUrl: "https://celo-rpc.publicnode.com",
    endpointId: 30125,
    explorerTxUrl: "https://celoscan.io/tx/{tx}",
  },
  "chiliz": {
    name: "chiliz",
    label: "Chiliz",
    chainId: 88888,
    rpcUrl: "https://rpc.chiliz.com",
    endpointId: 30409,
    explorerTxUrl: "https://chiliscan.com/tx/{tx}",
  },
  "citrea": {
    name: "citrea",
    label: "Citrea",
    chainId: 4114,
    rpcUrl: "https://rpc.mainnet.citrea.xyz",
    endpointId: 30403,
    explorerTxUrl: "https://explorer.mainnet.citrea.xyz/tx/{tx}",
  },
  "codex": {
    name: "codex",
    label: "Codex",
    chainId: 81224,
    rpcUrl: "https://rpc.codex.xyz",
    endpointId: 30323,
    explorerTxUrl: "https://explorer.codex.xyz/tx/{tx}",
  },
  "conflux": {
    name: "conflux",
    label: "Conflux eSpace",
    chainId: 1030,
    rpcUrl: "https://evm.confluxrpc.com",
    endpointId: 30212,
    explorerTxUrl: "https://evm.confluxscan.net/tx/{tx}",
  },
  "coredao": {
    name: "coredao",
    label: "CoreDAO",
    chainId: 1116,
    rpcUrl: "https://rpc.coredao.org/",
    endpointId: 30153,
    explorerTxUrl: "https://scan.coredao.org/tx/{tx}",
  },
  "cronosevm": {
    name: "cronosevm",
    label: "Cronos EVM",
    chainId: 25,
    rpcUrl: "https://cronos-evm-rpc.publicnode.com",
    endpointId: 30359,
    explorerTxUrl: "https://cronoscan.com/tx/{tx}",
  },
  "cyber": {
    name: "cyber",
    label: "Cyber",
    chainId: 7560,
    rpcUrl: "https://rpc.cyber.co/",
    endpointId: 30283,
    explorerTxUrl: "https://cyberscan.co/tx/{tx}",
  },
  "degen": {
    name: "degen",
    label: "Degen",
    chainId: 666666666,
    rpcUrl: "https://rpc.degen.tips",
    endpointId: 30267,
    explorerTxUrl: "https://explorer.degen.tips/tx/{tx}",
  },
  "dexalot": {
    name: "dexalot",
    label: "Dexalot Subnet",
    chainId: 432204,
    rpcUrl: "https://subnets.avax.network/dexalot/mainnet/rpc",
    endpointId: 30118,
    explorerTxUrl: "https://subnets.avax.network/dexalot/tx/{tx}",
  },
  "dfk": {
    name: "dfk",
    label: "DFK Chain",
    chainId: 53935,
    rpcUrl: "https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc",
    endpointId: 30115,
    explorerTxUrl: "https://explorer.dfkchain.com/tx/{tx}",
  },
  "dm2verse": {
    name: "dm2verse",
    label: "DM2 Verse",
    chainId: 68770,
    rpcUrl: "https://rpc.dm2verse.dmm.com",
    endpointId: 30315,
    explorerTxUrl: "https://explorer.dm2verse.dmm.com/tx/{tx}",
  },
  "doma": {
    name: "doma",
    label: "Doma",
    chainId: 97477,
    rpcUrl: "https://rpc.doma.xyz",
    endpointId: 30393,
    explorerTxUrl: "https://explorer.doma.xyz/tx/{tx}",
  },
  "dos": {
    name: "dos",
    label: "DOS Chain",
    chainId: 7979,
    rpcUrl: "https://main.doschain.com",
    endpointId: 30149,
    explorerTxUrl: "https://doscan.io/tx/{tx}",
  },
  "edu": {
    name: "edu",
    label: "EDU Chain",
    chainId: 41923,
    rpcUrl: "https://rpc.edu-chain.raas.gelato.cloud",
    endpointId: 30328,
    explorerTxUrl: "https://educhain.blockscout.com/tx/{tx}",
  },
  "ethereum": {
    name: "ethereum",
    label: "Ethereum",
    chainId: 1,
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    endpointId: 30101,
    explorerTxUrl: "https://etherscan.io/tx/{tx}",
  },
  "etherlink": {
    name: "etherlink",
    label: "Etherlink",
    chainId: 42793,
    rpcUrl: "https://node.mainnet.etherlink.com",
    endpointId: 30292,
    explorerTxUrl: "https://explorer.etherlink.com/tx/{tx}",
  },
  "fantom": {
    name: "fantom",
    label: "Fantom",
    chainId: 250,
    rpcUrl: "https://rpc.ftm.tools",
    endpointId: 30112,
    explorerTxUrl: "https://ftmscan.com/tx/{tx}",
  },
  "flare": {
    name: "flare",
    label: "Flare",
    chainId: 14,
    rpcUrl: "https://flare-api.flare.network/ext/C/rpc",
    endpointId: 30295,
    explorerTxUrl: "https://flare-explorer.flare.network/tx/{tx}",
  },
  "flow": {
    name: "flow",
    label: "EVM on Flow",
    chainId: 747,
    rpcUrl: "https://mainnet.evm.nodes.onflow.org",
    endpointId: 30336,
    explorerTxUrl: "https://evm.flowscan.io/tx/{tx}",
  },
  "fraxtal": {
    name: "fraxtal",
    label: "Fraxtal",
    chainId: 252,
    rpcUrl: "https://rpc.frax.com",
    endpointId: 30255,
    explorerTxUrl: "https://fraxscan.com/tx/{tx}",
  },
  "fuse": {
    name: "fuse",
    label: "Fuse",
    chainId: 122,
    rpcUrl: "https://rpc.fuse.io",
    endpointId: 30138,
    explorerTxUrl: "https://explorer.fuse.io/tx/{tx}",
  },
  "gensyn": {
    name: "gensyn",
    label: "Gensyn",
    chainId: 685689,
    rpcUrl: "https://gensyn-mainnet.g.alchemy.com/public",
    endpointId: 30412,
    explorerTxUrl: "https://gensyn-mainnet.explorer.alchemy.com/tx/{tx}",
  },
  "glue": {
    name: "glue",
    label: "Glue",
    chainId: 1300,
    rpcUrl: "https://rpc.glue.net",
    endpointId: 30342,
    explorerTxUrl: "https://explorer.glue.net/tx/{tx}",
  },
  "gnosis": {
    name: "gnosis",
    label: "Gnosis",
    chainId: 100,
    rpcUrl: "https://gnosis-rpc.publicnode.com",
    endpointId: 30145,
    explorerTxUrl: "https://gnosisscan.io/tx/{tx}",
  },
  "goat": {
    name: "goat",
    label: "Goat",
    chainId: 2345,
    rpcUrl: "https://rpc.goat.network",
    endpointId: 30361,
    explorerTxUrl: "https://explorer.goat.network/tx/{tx}",
  },
  "gravity": {
    name: "gravity",
    label: "Gravity",
    chainId: 1625,
    rpcUrl: "https://rpc.gravity.xyz",
    endpointId: 30294,
    explorerTxUrl: "https://explorer.gravity.xyz/tx/{tx}",
  },
  "gunz": {
    name: "gunz",
    label: "Gunz",
    chainId: 43419,
    rpcUrl: "https://rpc.gunzchain.io/ext/bc/2M47TxWHGnhNtq6pM5zPXdATBtuqubxn5EPFgFmEawCQr9WFML/rpc",
    endpointId: 30371,
    explorerTxUrl: "https://gunzscan.io/tx/{tx}",
  },
  "harmony": {
    name: "harmony",
    label: "Harmony",
    chainId: 1666600000,
    rpcUrl: "https://rpc.ankr.com/harmony",
    endpointId: 30116,
    explorerTxUrl: "https://explorer.harmony.one/tx/{tx}",
  },
  "hedera": {
    name: "hedera",
    label: "Hedera",
    chainId: 295,
    rpcUrl: "https://mainnet.hashio.io/api",
    endpointId: 30316,
    explorerTxUrl: "https://hashscan.io/mainnet/transaction/{tx}",
  },
  "hemi": {
    name: "hemi",
    label: "Hemi",
    chainId: 43111,
    rpcUrl: "https://rpc.hemi.network/rpc",
    endpointId: 30329,
    explorerTxUrl: "https://explorer.hemi.xyz/tx/{tx}",
  },
  "homeverse": {
    name: "homeverse",
    label: "Homeverse",
    chainId: 19011,
    rpcUrl: "https://rpc.mainnet.oasys.homeverse.games/",
    endpointId: 30265,
    explorerTxUrl: "https://explorer.oasys.homeverse.games/tx/{tx}",
  },
  "horizen": {
    name: "horizen",
    label: "Horizen",
    chainId: 26514,
    rpcUrl: "https://horizen.calderachain.xyz/http",
    endpointId: 30399,
    explorerTxUrl: "https://horizen.calderaexplorer.xyz/tx/{tx}",
  },
  "hubble": {
    name: "hubble",
    label: "Hubble",
    chainId: 1992,
    rpcUrl: "https://rpc.hubble.exchange",
    endpointId: 30182,
  },
  "humanity": {
    name: "humanity",
    label: "Humanity",
    chainId: 6985385,
    rpcUrl: "https://humanity-mainnet.g.alchemy.com/public",
    endpointId: 30382,
    explorerTxUrl: "https://humanity-mainnet.explorer.alchemy.com/tx/{tx}",
  },
  "hyperliquid": {
    name: "hyperliquid",
    label: "HyperEVM",
    chainId: 999,
    rpcUrl: "https://gwan-ssl.wandevs.org:46891/",
    endpointId: 30367,
    explorerTxUrl: "https://hyperevmscan.io/tx/{tx}",
  },
  "ink": {
    name: "ink",
    label: "Ink",
    chainId: 57073,
    rpcUrl: "https://rpc-gel.inkonchain.com",
    endpointId: 30339,
    explorerTxUrl: "https://explorer.inkonchain.com/tx/{tx}",
  },
  "iota": {
    name: "iota",
    label: "IOTA EVM",
    chainId: 8822,
    rpcUrl: "https://json-rpc.evm.iotaledger.net",
    endpointId: 30284,
    explorerTxUrl: "https://explorer.evm.iota.org/tx/{tx}",
  },
  "irys": {
    name: "irys",
    label: "Irys",
    chainId: 3282,
    rpcUrl: "https://mainnet-beta-rpc.irys.xyz/v1/execution-rpc",
    endpointId: 30408,
    explorerTxUrl: "https://evm-explorer.irys.xyz/tx/{tx}",
  },
  "islander": {
    name: "islander",
    label: "Vana",
    chainId: 1480,
    rpcUrl: "https://rpc.vana.org/",
    endpointId: 30330,
    explorerTxUrl: "https://vanascan.io/tx/{tx}",
  },
  "joc": {
    name: "joc",
    label: "Japan Open Chain",
    chainId: 81,
    rpcUrl: "https://rpc-1.japanopenchain.org:8545",
    endpointId: 30285,
    explorerTxUrl: "https://explorer.japanopenchain.org/tx/{tx}",
  },
  "katana": {
    name: "katana",
    label: "Katana",
    chainId: 747474,
    rpcUrl: "https://rpc.katana.network",
    endpointId: 30375,
    explorerTxUrl: "https://katanascan.com/tx/{tx}",
  },
  "kava": {
    name: "kava",
    label: "Kava",
    chainId: 2222,
    rpcUrl: "https://kava-rpc.gateway.pokt.network",
    endpointId: 30177,
    explorerTxUrl: "https://kavascan.com/tx/{tx}",
  },
  "kite": {
    name: "kite",
    label: "Kite",
    chainId: 2366,
    rpcUrl: "https://rpc.gokite.ai",
    endpointId: 30406,
    explorerTxUrl: "https://kitescan.ai/tx/{tx}",
  },
  "klaytn": {
    name: "klaytn",
    label: "Kaia",
    chainId: 8217,
    rpcUrl: "https://public-en.node.kaia.io",
    endpointId: 30150,
    explorerTxUrl: "https://kaiascan.io/tx/{tx}",
  },
  "lightlink": {
    name: "lightlink",
    label: "Lightlink",
    chainId: 1890,
    rpcUrl: "https://replicator.phoenix.lightlink.io/rpc/v1",
    endpointId: 30309,
    explorerTxUrl: "https://phoenix.lightlink.io/tx/{tx}",
  },
  "linea": {
    name: "linea",
    label: "Linea",
    chainId: 59144,
    rpcUrl: "https://linea-rpc.publicnode.com",
    endpointId: 30183,
    explorerTxUrl: "https://lineascan.build/tx/{tx}",
  },
  "lisk": {
    name: "lisk",
    label: "Lisk",
    chainId: 1135,
    rpcUrl: "https://rpc.api.lisk.com",
    endpointId: 30321,
    explorerTxUrl: "https://blockscout.lisk.com/tx/{tx}",
  },
  "lyra": {
    name: "lyra",
    label: "Lyra",
    chainId: 957,
    rpcUrl: "https://rpc.lyra.finance",
    endpointId: 30311,
    explorerTxUrl: "https://explorer.lyra.finance/tx/{tx}",
  },
  "manta": {
    name: "manta",
    label: "Manta Pacific",
    chainId: 169,
    rpcUrl: "https://pacific-rpc.manta.network/http",
    endpointId: 30217,
    explorerTxUrl: "https://pacific-explorer.manta.network/tx/{tx}",
  },
  "mantle": {
    name: "mantle",
    label: "Mantle",
    chainId: 5000,
    rpcUrl: "https://mantle-rpc.publicnode.com",
    endpointId: 30181,
    explorerTxUrl: "https://mantlescan.xyz/tx/{tx}",
  },
  "megaeth": {
    name: "megaeth",
    label: "Megaeth",
    chainId: 4326,
    rpcUrl: "https://mainnet.megaeth.com/rpc",
    endpointId: 30398,
    explorerTxUrl: "https://mega.etherscan.io/tx/{tx}",
  },
  "merlin": {
    name: "merlin",
    label: "Merlin",
    chainId: 4200,
    rpcUrl: "https://rpc.merlinchain.io",
    endpointId: 30266,
    explorerTxUrl: "https://scan.merlinchain.io/tx/{tx}",
  },
  "meter": {
    name: "meter",
    label: "Meter",
    chainId: 82,
    rpcUrl: "https://rpc.meter.io",
    endpointId: 30176,
    explorerTxUrl: "https://scan.meter.io/tx/{tx}",
  },
  "metis": {
    name: "metis",
    label: "Metis",
    chainId: 1088,
    rpcUrl: "https://metis-rpc.publicnode.com",
    endpointId: 30151,
    explorerTxUrl: "https://andromeda-explorer.metis.io/tx/{tx}",
  },
  "mode": {
    name: "mode",
    label: "Mode",
    chainId: 34443,
    rpcUrl: "https://mode.drpc.org",
    endpointId: 30260,
    explorerTxUrl: "https://explorer.mode.network/tx/{tx}",
  },
  "monad": {
    name: "monad",
    label: "Monad",
    chainId: 143,
    rpcUrl: "https://rpc.monad.xyz",
    endpointId: 30390,
    explorerTxUrl: "https://monadvision.com/tx/{tx}",
  },
  "moonbeam": {
    name: "moonbeam",
    label: "Moonbeam",
    chainId: 1284,
    rpcUrl: "https://moonbeam-rpc.publicnode.com",
    endpointId: 30126,
    explorerTxUrl: "https://moonbeam.moonscan.io/tx/{tx}",
  },
  "moonriver": {
    name: "moonriver",
    label: "Moonriver",
    chainId: 1285,
    rpcUrl: "https://rpc.api.moonriver.moonbeam.network",
    endpointId: 30167,
    explorerTxUrl: "https://moonriver.moonscan.io/tx/{tx}",
  },
  "morph": {
    name: "morph",
    label: "Morph",
    chainId: 2818,
    rpcUrl: "https://rpc.morphl2.io",
    endpointId: 30322,
    explorerTxUrl: "https://explorer.morphl2.io/tx/{tx}",
  },
  "mp1": {
    name: "mp1",
    label: "Corn",
    chainId: 21000000,
    rpcUrl: "https://mainnet.corn-rpc.com",
    endpointId: 30331,
    explorerTxUrl: "https://cornscan.io/tx/{tx}",
  },
  "nexera": {
    name: "nexera",
    label: "Nexera",
    chainId: 7208,
    rpcUrl: "https://rpc.nexera.network",
    endpointId: 30395,
  },
  "nibiru": {
    name: "nibiru",
    label: "Nibiru",
    chainId: 6900,
    rpcUrl: "https://evm-rpc.nibiru.fi",
    endpointId: 30369,
  },
  "nova": {
    name: "nova",
    label: "Arbitrum Nova",
    chainId: 42170,
    rpcUrl: "https://nova.arbitrum.io/rpc",
    endpointId: 30175,
    explorerTxUrl: "https://nova-explorer.arbitrum.io/tx/{tx}",
  },
  "og": {
    name: "og",
    label: "0G",
    chainId: 16661,
    rpcUrl: "https://evmrpc.0g.ai",
    endpointId: 30388,
    explorerTxUrl: "https://chainscan.0g.ai/tx/{tx}",
  },
  "okx": {
    name: "okx",
    label: "OKX",
    chainId: 66,
    rpcUrl: "https://exchainrpc.okex.org",
    endpointId: 30155,
    explorerTxUrl: "https://www.oklink.com/en/okc/tx/{tx}",
  },
  "opbnb": {
    name: "opbnb",
    label: "opBNB",
    chainId: 204,
    rpcUrl: "https://opbnb-rpc.publicnode.com",
    endpointId: 30202,
    explorerTxUrl: "https://mainnet.opbnbscan.com/tx/{tx}",
  },
  "openledger": {
    name: "openledger",
    label: "OpenLedger",
    chainId: 1612,
    rpcUrl: "https://rpc.openledger.xyz",
    endpointId: 30392,
    explorerTxUrl: "https://scan.openledger.xyz/tx/{tx}",
  },
  "optimism": {
    name: "optimism",
    label: "Optimism",
    chainId: 10,
    rpcUrl: "https://optimism-rpc.publicnode.com",
    endpointId: 30111,
    explorerTxUrl: "https://optimistic.etherscan.io/tx/{tx}",
  },
  "orderly": {
    name: "orderly",
    label: "Orderly",
    chainId: 291,
    rpcUrl: "https://rpc.orderly.network",
    endpointId: 30213,
    explorerTxUrl: "https://explorer.orderly.network/tx/{tx}",
  },
  "peaq": {
    name: "peaq",
    label: "Peaq",
    chainId: 3338,
    rpcUrl: "https://quicknode1.peaq.xyz",
    endpointId: 30302,
    explorerTxUrl: "https://peaq.subscan.io/evm/tx/{tx}",
  },
  "plasma": {
    name: "plasma",
    label: "Plasma",
    chainId: 9745,
    rpcUrl: "https://rpc.plasma.to",
    endpointId: 30383,
    explorerTxUrl: "https://plasmascan.to/tx/{tx}",
  },
  "plumephoenix": {
    name: "plumephoenix",
    label: "Plume",
    chainId: 98866,
    rpcUrl: "https://rpc.plume.org",
    endpointId: 30370,
    explorerTxUrl: "https://explorer.plume.org/tx/{tx}",
  },
  "polygon": {
    name: "polygon",
    label: "Polygon",
    chainId: 137,
    rpcUrl: "https://polygon-bor-rpc.publicnode.com",
    endpointId: 30109,
    explorerTxUrl: "https://polygonscan.com/tx/{tx}",
  },
  "rarible": {
    name: "rarible",
    label: "Rari Chain",
    chainId: 1380012617,
    rpcUrl: "https://rari.calderachain.xyz/http",
    endpointId: 30235,
    explorerTxUrl: "https://mainnet.explorer.rarichain.org/tx/{tx}",
  },
  "real": {
    name: "real",
    label: "re.al",
    chainId: 111188,
    rpcUrl: "https://rpc.realforreal.gelato.digital",
    endpointId: 30237,
    explorerTxUrl: "https://explorer.re.al/tx/{tx}",
  },
  "redbelly": {
    name: "redbelly",
    label: "Redbelly",
    chainId: 151,
    rpcUrl: "https://governors.mainnet.redbelly.network",
    endpointId: 30402,
    explorerTxUrl: "https://redbelly.routescan.io/tx/{tx}",
  },
  "reya": {
    name: "reya",
    label: "Reya",
    chainId: 1729,
    rpcUrl: "https://rpc.reya.network",
    endpointId: 30313,
    explorerTxUrl: "https://explorer.reya.network/tx/{tx}",
  },
  "rise": {
    name: "rise",
    label: "Rise",
    chainId: 4153,
    rpcUrl: "https://rpc.risechain.com/",
    endpointId: 30401,
    explorerTxUrl: "https://explorer.risechain.com/tx/{tx}",
  },
  "rootstock": {
    name: "rootstock",
    label: "Rootstock",
    chainId: 30,
    rpcUrl: "https://public-node.rsk.co",
    endpointId: 30333,
    explorerTxUrl: "https://explorer.rsk.co/tx/{tx}",
  },
  "sagaevm": {
    name: "sagaevm",
    label: "Sagaevm",
    chainId: 5464,
    rpcUrl: "https://sagaevm.jsonrpc.sagarpc.io",
    endpointId: 30405,
    explorerTxUrl: "https://sagaevm.sagaexplorer.io/tx/{tx}",
  },
  "scroll": {
    name: "scroll",
    label: "Scroll",
    chainId: 534352,
    rpcUrl: "https://scroll-rpc.publicnode.com",
    endpointId: 30214,
    explorerTxUrl: "https://scrollscan.com/tx/{tx}",
  },
  "sei": {
    name: "sei",
    label: "Sei",
    chainId: 1329,
    rpcUrl: "https://evm-rpc.sei-apis.com",
    endpointId: 30280,
    explorerTxUrl: "https://seitrace.com/tx/{tx}",
  },
  "shimmer": {
    name: "shimmer",
    label: "Shimmer",
    chainId: 148,
    rpcUrl: "https://json-rpc.evm.shimmer.network",
    endpointId: 30230,
    explorerTxUrl: "https://explorer.evm.shimmer.network/tx/{tx}",
  },
  "silicon": {
    name: "silicon",
    label: "Silicon",
    chainId: 2355,
    rpcUrl: "https://rpc.silicon.network",
    endpointId: 30379,
    explorerTxUrl: "https://scope.silicon.network/tx/{tx}",
  },
  "skale": {
    name: "skale",
    label: "Skale",
    chainId: 2046399126,
    rpcUrl: "https://mainnet.skalenodes.com/v1/elated-tan-skat",
    endpointId: 30273,
    explorerTxUrl: "https://elated-tan-skat.explorer.mainnet.skalenodes.com/tx/{tx}",
  },
  "somnia": {
    name: "somnia",
    label: "Somnia",
    chainId: 5031,
    rpcUrl: "https://api.infra.mainnet.somnia.network",
    endpointId: 30380,
    explorerTxUrl: "https://mainnet.somnia.w3us.site/tx/{tx}",
  },
  "soneium": {
    name: "soneium",
    label: "Soneium",
    chainId: 1868,
    rpcUrl: "https://rpc.soneium.org",
    endpointId: 30340,
    explorerTxUrl: "https://soneium.blockscout.com/tx/{tx}",
  },
  "sonic": {
    name: "sonic",
    label: "Sonic",
    chainId: 146,
    rpcUrl: "https://sonic-rpc.publicnode.com",
    endpointId: 30332,
    explorerTxUrl: "https://sonicscan.org/tx/{tx}",
  },
  "sophon": {
    name: "sophon",
    label: "Sophon",
    chainId: 50104,
    rpcUrl: "https://rpc.sophon.xyz",
    endpointId: 30334,
    explorerTxUrl: "https://explorer.sophon.xyz/tx/{tx}",
  },
  "space": {
    name: "space",
    label: "Otherworld Space",
    chainId: 8227,
    rpcUrl: "https://subnets.avax.network/space/mainnet/rpc",
    endpointId: 30341,
    explorerTxUrl: "https://subnets.avax.network/space/tx/{tx}",
  },
  "stable": {
    name: "stable",
    label: "Stable",
    chainId: 988,
    rpcUrl: "https://rpc.stable.xyz",
    endpointId: 30396,
    explorerTxUrl: "https://stablescan.xyz/tx/{tx}",
  },
  "story": {
    name: "story",
    label: "Story",
    chainId: 1514,
    rpcUrl: "https://mainnet.storyrpc.io",
    endpointId: 30364,
    explorerTxUrl: "https://mainnet.storyscan.xyz/tx/{tx}",
  },
  "subtensorevm": {
    name: "subtensorevm",
    label: "Subtensor EVM",
    chainId: 964,
    rpcUrl: "https://lite.chain.opentensor.ai",
    endpointId: 30374,
  },
  "superposition": {
    name: "superposition",
    label: "Superposition",
    chainId: 55244,
    rpcUrl: "https://rpc.superposition.so",
    endpointId: 30327,
    explorerTxUrl: "https://explorer.superposition.so/tx/{tx}",
  },
  "swell": {
    name: "swell",
    label: "Swell",
    chainId: 1923,
    rpcUrl: "https://rpc.ankr.com/swell",
    endpointId: 30335,
    explorerTxUrl: "https://explorer.swellnetwork.io/tx/{tx}",
  },
  "tac": {
    name: "tac",
    label: "Tac",
    chainId: 239,
    rpcUrl: "https://rpc.tac.build",
    endpointId: 30377,
    explorerTxUrl: "https://explorer.tac.build/tx/{tx}",
  },
  "taiko": {
    name: "taiko",
    label: "Taiko",
    chainId: 167000,
    rpcUrl: "https://taiko-rpc.publicnode.com",
    endpointId: 30290,
    explorerTxUrl: "https://taikoscan.io/tx/{tx}",
  },
  "telos": {
    name: "telos",
    label: "TelosEVM",
    chainId: 40,
    rpcUrl: "https://rpc.telos.net",
    endpointId: 30199,
    explorerTxUrl: "https://teloscan.io/tx/{tx}",
  },
  "tempo": {
    name: "tempo",
    label: "Tempo",
    chainId: 4217,
    rpcUrl: "https://rpc.mainnet.tempo.xyz",
    endpointId: 30410,
    explorerTxUrl: "https://explore.tempo.xyz/tx/{tx}",
  },
  "tenet": {
    name: "tenet",
    label: "Tenet",
    chainId: 1559,
    rpcUrl: "https://rpc.tenet.org",
    endpointId: 30173,
    explorerTxUrl: "https://tenetscan.io/tx/{tx}",
  },
  "tiltyard": {
    name: "tiltyard",
    label: "Tiltyard",
    chainId: 710420,
    rpcUrl: "https://subnets.avax.network/tiltyard/mainnet/rpc",
    endpointId: 30238,
    explorerTxUrl: "https://subnets.avax.network/tiltyard/tx/{tx}",
  },
  "tomo": {
    name: "tomo",
    label: "Viction",
    chainId: 88,
    rpcUrl: "https://rpc.viction.xyz",
    endpointId: 30196,
  },
  "unichain": {
    name: "unichain",
    label: "Unichain",
    chainId: 130,
    rpcUrl: "https://unichain-rpc.publicnode.com",
    endpointId: 30320,
    explorerTxUrl: "https://uniscan.xyz/tx/{tx}",
  },
  "worldchain": {
    name: "worldchain",
    label: "Worldchain",
    chainId: 480,
    rpcUrl: "https://480.rpc.thirdweb.com",
    endpointId: 30319,
    explorerTxUrl: "https://worldscan.org/tx/{tx}",
  },
  "xai": {
    name: "xai",
    label: "Xai",
    chainId: 660279,
    rpcUrl: "https://xai-chain.net/rpc",
    endpointId: 30236,
    explorerTxUrl: "https://explorer.xai-chain.net/tx/{tx}",
  },
  "xchain": {
    name: "xchain",
    label: "XChain",
    chainId: 94524,
    rpcUrl: "https://xchain-rpc.kuma.bid",
    endpointId: 30291,
    explorerTxUrl: "https://xchain-explorer.kuma.bid/tx/{tx}",
  },
  "xdc": {
    name: "xdc",
    label: "XDC",
    chainId: 50,
    rpcUrl: "https://erpc.xinfin.network",
    endpointId: 30365,
    explorerTxUrl: "https://xdcscan.com/tx/{tx}",
  },
  "xlayer": {
    name: "xlayer",
    label: "X Layer",
    chainId: 196,
    rpcUrl: "https://rpc.xlayer.tech",
    endpointId: 30274,
    explorerTxUrl: "https://www.oklink.com/xlayer/tx/{tx}",
  },
  "xpla": {
    name: "xpla",
    label: "XPLA",
    chainId: 37,
    rpcUrl: "https://dimension-evm-rpc.xpla.dev",
    endpointId: 30216,
    explorerTxUrl: "https://explorer.xpla.io/mainnet/tx/{tx}",
  },
  "zircuit": {
    name: "zircuit",
    label: "Zircuit",
    chainId: 48900,
    rpcUrl: "https://mainnet.zircuit.com",
    endpointId: 30303,
    explorerTxUrl: "https://explorer.zircuit.com/tx/{tx}",
  },
  "zkatana": {
    name: "zkatana",
    label: "Astar zkEVM",
    chainId: 3776,
    rpcUrl: "https://rpc.startale.com/astar-zkevm",
    endpointId: 30257,
    explorerTxUrl: "https://astar-zkevm.explorer.startale.com/tx/{tx}",
  },
  "zkevm": {
    name: "zkevm",
    label: "Polygon zkEVM",
    chainId: 1101,
    rpcUrl: "https://zkevm-rpc.com",
    endpointId: 30158,
    explorerTxUrl: "https://zkevm.polygonscan.com/tx/{tx}",
  },
  "zksync": {
    name: "zksync",
    label: "zkSync Era",
    chainId: 324,
    rpcUrl: "https://zksync-era-rpc.publicnode.com",
    endpointId: 30165,
    explorerTxUrl: "https://explorer.zksync.io/tx/{tx}",
  },
  "zora": {
    name: "zora",
    label: "Zora",
    chainId: 7777777,
    rpcUrl: "https://zora-rpc.publicnode.com",
    endpointId: 30195,
    explorerTxUrl: "https://explorer.zora.energy/tx/{tx}",
  },
};

export function getEvmChain(name: string): EvmChainConfig {
  const chain = evmChains[name];
  if (!chain) throw new Error(`Unsupported EVM chain: ${name}`);
  return chain;
}
